### PR TITLE
Fix ContractForm to set checkbox value

### PR DESCRIPTION
**Pull request by samajammin**
Fixes https://github.com/trufflesuite/drizzle-react-components/issues/53

### CODE REVIEW

**Comment by samajammin** [comment]
Hi @DiscRiskandBisque @honestbonsai - checking in on this. I'm not seeing much activity on issues or PRs. Is this project actively maintained? Totally understand if it's not a top priority. Thanks for creating it. Cheers.

**Comment by honestbonsai** [comment]
@sbrichards Thanks for opening the issue and PR! This repo is still actively maintained. We are in the process of cleaning it up right now. Sorry if it's taking a while to get things reviewed.

**Comment by honestbonsai** [comment]
@sbrichards Can you provide this for the new context components as well? `master` has just been updated with React 16.3+ context support.

Would also be helpful to provide an example in both the test apps so users can see the full functionality.

**Comment by samajammin** [comment]
@honestbonsai I'm having an issue setting up the test app in order to provide an example. I pulled down the latest master of this repo & followed the [test app instructions](https://github.com/trufflesuite/drizzle-react-components#test-apps) in the README. I get this error when trying to boot up the app (i.e. `npm start`):

image 2019-02-25 at 7 15 15 pm

Console:
```
MyComponent.js:6 Uncaught TypeError: Cannot read property 'AccountData' of undefined
    at Module../src/MyComponent.js (MyComponent.js:6)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/App.js (App.css?da7c:45)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/index.js (index.css?02e3:45)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Object.0 (serviceWorker.js:135)
    at __webpack_require__ (bootstrap:782)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

Here's what my system is running:
```
~/code/drizzle-react-components/test-app/app « git:(master)
$ truffle version
Truffle v5.0.1 (core: 5.0.1)
Solidity v0.5.0 (solc-js)
Node v10.13.0
```
Let me know if you'd like me to open a separate issue for this. Thanks!

**Comment by honestbonsai** [comment]
@sbrichards Hmm, I just tried myself, and it seems to work. 

I actually just released 1.3 which has the new context components, maybe wipe `node_modules` of the test apps and try again? I was probably using `npm link` to link the local `dist` build to do it before releasing on npm.

If that doesn't work, can you open a new issue for that? Thanks!

**Comment by lestari-thomas** [comment]
I've tried 1.3, and it's still an issue. A ticked checkbox still results in a negative value being passed to the method parameter.

**Comment by adrianmcli** [comment]
@honestbonsai Can we get this merged? It looks like a simple fix for a bug that multiple people are having.

**Comment by honestbonsai** [comment]
@adrianmcli Still waiting on the new context component version of the fix.

@sbrichards Any updates on getting this for the new context components?

**Comment by samajammin** [comment]
@honestbonsai @adrianmcli I added the new context component version of the fix & added examples to the 2 test apps. I then rebased off master. I'm not sure why it shows some many diffs/commits? My only changes are the last 2 commits. Please let me know if there's an issue. I can pick these changes off in a new PR if needed.

**Comment by adrianmcli** [comment]
@sbrichards Your forked repo may have been outdated, I'm not sure. These weird things happen from time to time. Might be a good idea to pick the commits into a new PR (like you said), or alternatively you can try to fix it and force-push to this branch again.

**Comment by samajammin** [comment]
@honestbonsai @adrianmcli fixed. Take a look when you can! Cheers.

**Comment by honestbonsai** [comment]
@sbrichards Looks great, thanks a lot for the PR!

**Comment by sampsojp** [comment]
I'm still seeing this same issue with both new context and legacy. Just cloned it a couple of days ago. Is it supposed to be resolved?

**Comment by adrianmcli** [comment]
@sampsojp good catch, it looks like we haven't published since the change.

@honestbonsai do you want to take a shot at pushing this out? If not, I can do it.

**Comment by honestbonsai** [comment]
@adrianmcli Can you do a release? I'm still looking at a different PR for this repo. Thanks!

**Pull request merged**
