### PR TITLE
Fix an issue when strings were sent directly to contract method expecting bytes32

### PR DESCRIPTION
**Pull request by maxme**
Before this patch it was impossible to use this component to call a method expecting a bytes32, transaction was failing and was added to the transaction stack

### CODE REVIEW

**Comment by honestbonsai** [comment]
@maxme Thanks for this PR! Can you add this fix to the new context components as well?

**Comment by maxme** [comment]
@honestbonsai, fixed for the new context components and updated the branch.

**Comment by honestbonsai** [comment]
@maxme Seems to have some merge conflicts with your other PR #45  which I just merged.

**Comment by maxme** [comment]
@honestbonsai  conflicts were resolved in 249b88a

**Comment by honestbonsai** [comment]
LGTM, thanks for the help! @maxme

**Pull request merged**
