### PR TITLE
Issue #6: ContractData displayData array type check and array rendering

### PR DESCRIPTION
**Pull request by latenssi**

### CODE REVIEW

**Comment by ksaynice** [comment]
+1

**Comment by mnaamani** [comment]
I just noticed that I created duplicate PR #21. The only difference (apart from syntax in the arrow function) is the way type checking is done. 

I opted for `Array.isArray` instead of `instanceof` 
Both approaches are probably [fine](https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array)

**Comment by ijxy** [comment]
@DiscRiskandBisque any chance of you merging this in? It was raised as a problem in March and is still a problem today.

**Comment by PabiGamito** [comment]
Please do merge this in whenever possible. It is still a problem, with what seems like a relatively easy fix.

**Comment by samajammin** [comment]
Can we please merge this? Or can someone with the power to merge share what else is needed in order to merge? Happy to help make it happen.

I hit this same issue & solved it locally. Came here to open a PR & found this as one of 3 open PRs that fixe the same bug 😅 
https://github.com/trufflesuite/drizzle-react-components/pull/46
https://github.com/trufflesuite/drizzle-react-components/pull/21

**Comment by honestbonsai** [comment]
Closing since it's the same as #6 which was closed by #46

**Pull request closed without merging**
