### PR TITLE
Feature/new api loading container

### PR DESCRIPTION
**Pull request by dannycarrera**
The new-context-api doesn't include a loading container to check if a client has a web3 provider and permission to access account data.

The design and messages were taken from the legacy component as much as possible, but because the new-context-api only indicates if drizzle is initialized the following changes to the messages were made:

##### Legacy api
* No web3 error
* No Ether accounts found
* Loading

##### new-context-api
* Initializing... - with a more generic message indicating that the user needs MetaMask, Mist or Parity
* No Ether accounts found

### CODE REVIEW

**Comment by adrianmcli** [comment]
@honestbonsai can you take a quick look at this? If not, I can review it myself.

**Comment by honestbonsai** [comment]
@dannycarrera Thanks for your submission! Some more context would help us in reviewing this.

1. Point to the issue that this is resolving in the PR (e.g. `Resolves #xx`)
1. Add some text to the PR that describes this at a high level

**Comment by honestbonsai** [comment]
@dannycarrera Some things that need to be addressed

1. Some odd behavior

    1. When Metamask is present and locked I get the `Initializing...no Metamask` screen.

    1. When Metamask is not present (i.e. I disabled the extension entirely), I get the `We can't find any Ethereum accounts!` screen.

    I'd expect the 2 screens to be reversed. Looking at the old context `LoadingContainer` there seem to be some slight changes in this PR. The old one relied on `web3` to determine things. Perhaps give that a shot?

1. Can you update the README as well? It says `LoadingContainer` is only for legacy components right now, but with this PR that will change.

**Comment by dannycarrera** [comment]
@honestbonsai 
My pleasure! Thank you for your work on truffle/drizzle. They've definitely helped a lot in getting going with developing a dApp.

1. There was no issue for this feature. Should I create one? I wasn't sure if it was required from the contributor guidelines.
2. Added some text to the PR

**Comment by dannycarrera** [comment]
@honestbonsai I retested on Chrome & Firefox. (Make sure you're pointed to a network with the test-app contracts deployed)

What you may be experiencing is the following, if your MetaMask network is set to a network that does *not* have the test-app contracts deployed:

1. When MetaMask is present and locked, I get the `Initializing... no MetaMask`

2. When MetaMask is not present (by disabling the extension), I get the `Initializing... no MetaMask`

I am not able to reproduce the case where `We can't find any Ethereum accounts!`  is displayed when MetaMask is not present.


The following intended behavior is produced when connected to a network with the test-app contracts deployed.

1. When MetaMask is present and locked, I get the `We can't find any Ethereum accounts!`

2. When MetaMask is not present (by disabling the extension), I get the `Initializing... no MetaMask`


For now, I have updated the error text for the `Initializing...` message to make sure the user is also connected to the right network.

In the future, when PR trufflesuite/drizzle#224 is merged and issue trufflesuite/drizzle#194 is addressed, better (and more consistent) UX messages can be displayed.

**Comment by honestbonsai** [comment]
@dannycarrera 

> There was no issue for this feature. Should I create one? I wasn't sure if it was required from the contributor guidelines.

Hmm we should clarify that in the guidelines. I was mainly asking since originally the PR lacked a description, so I wasn't sure what exactly the expected behavior was. But now since you've added one, don't worry about making an issue this time. Next time opening an issue first would be helpful for us to know what people want to see in this library.

Thanks for the updates! I'll take another look.

**Comment by dannycarrera** [comment]
@honestbonsai 
I tested before pushing, but while working on a different project I'm noticing some odd behavior. Let me look into it and update before you spend time on it. Sorry, not sure what the issue is. The "No Eth accounts found" error isn't coming up at all anymore.

Edit: Seems to be an issue introduced with MetaMask 6.6.0. Works as intended with 6.5.3

**Comment by dannycarrera** [comment]
@honestbonsai 
Confirmed this new issue (trufflesuite/drizzle#230) was introduced with MetaMask 6.6.0. Submitted a hotfix (trufflesuite/drizzle#231)

If you want to test it, test against MetaMask 6.5.3, or wait until the hotfix is merged and drizzle 1.4.1 is released. This will require #108 to be merged though.

**Comment by honestbonsai** [comment]
@dannycarrera Thanks for submitting those PRs to Drizzle. I'll check it out after the hotfix is merged.

**Comment by adrianmcli** [comment]
@dannycarrera I tried to run the test-app, but it simply seems to fail. Not sure what the problem is. However, we are moving to a monorepo really soon and we may not to be able to bring over PRs. I highly recommend holding off until we do so.

**Comment by dannycarrera** [comment]
Thanks for the headsup, @adrianmcli . Glad you're switching it up into a monorepo. I've forked off for now and have made a bunch of updates to the drizzle suite, which have helped make it more stable, consistent and predictable.

Once the new repo is ready, I'd be happy to bring over changes that are in line with drizzles future. It would also be great to have you guys review the changes.

I'd much rather contribute here and support the truffle/drizzle community than to maintain a separate fork. If you need additional help, let me know!

**Pull request closed without merging**
