### PR TITLE
fixed the 'address array not showed' bug.

### PR DESCRIPTION
**Pull request by Doc-Failure**
Even if the error is fixed, I find it in version 1.2
On line 59 of ContractData.js there is this condition: if (typeof displayData === 'array'), I did various tests and noticed that if you use typeof on an array it always returns false.
I think the control is to be changed in Array.isArray (displayData).
I'm not a javascript black belt and I apologize if I said crap :)

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks! I came across this as well. Also noticing that https://github.com/trufflesuite/drizzle-react-components/pull/21 & https://github.com/trufflesuite/drizzle-react-components/pull/7 solve the same issue but have not yet been merged.

**Comment by honestbonsai** [comment]
@St3C Thanks for your help! Can you provide this for the new context components as well?

**Comment by Doc-Failure** [comment]
@honestbonsai Of course! As soon as I can, I try to replicate the problem with the new component and to solve it.

**Comment by honestbonsai** [comment]
@St3C Looks good, thanks for the help!

Closes #6

**Comment by Doc-Failure** [comment]
@honestbonsai While I was working on the pull request I used the app-test and I had some problems with the import of the dependencies that I solved by updating "react-scripts" to the version "^ 2.1.5". Did you have similar problems? Can I include it in the pull request?
You are welcome :)

**Comment by honestbonsai** [comment]
@St3C Didn't have those problems, but if you experienced that, please open up a new issue and PR for it. Would prefer to keep things tightly scoped for issues and PRs. Thanks for your hard work!

**Pull request merged**
